### ISSUE TITLE
how could i complete async component with vue-router2.0

### ISSUE THREAD

**Issue by tongyimplin** [vuejs-templates/browserify#17]
hi, I am a freshman in vuejs, and I have no idea on how to complete async component development with browserify, and official document writes a demo with webpack on how to do that, could you show me how to deal with it, thank you so much!

**Comment by Steviey** [comment]
+1

**Comment by chrisvfritz** [comment]
[To quote](https://github.com/substack/node-browserify/issues/58#issuecomment-21978224) the creator of Browserify:

> browserify is for loading node-style modules in the browser. Asynchronous loading is not something that browserify does. If you want that, there are lots of alternatives such as requirejs that do asynchronous loading. This is not something that browserify will ever support.

That means if this is a feature that's important to you, you should use Webpack instead. 😕  I'll add a note to the docs explicitly mentioning that this is not possible with Browserify.

**Comment by tongyimplin** [comment]
It is a great of thanks!
