### ISSUE TITLE
http-server fails on Windows

### ISSUE THREAD

**Issue by jingsam** [vuejs-templates/browserify#2]
When I run `npm run dev`, http-server seems not working. That may be because `&` does not work on Windows.
https://github.com/vuejs-templates/browserify/blob/master/template%2Fpackage.json#L9

**Comment by rowanwins** [comment]
Hi @jingsam m

This can be resolved by using the [npm-run-all](https://www.npmjs.com/package/npm-run-all) package, something like this
````
    "watchify": "watchify -vd -p browserify-hmr -e src/main.js -o dist/build.js",
    "serve": "http-server -c 1 -a localhost",
    "dev": "npm-run-all --parallel watchify serve",
````

If @yyx990803 is interested I can submit a pull request including this module and modifying the start up scripts so they are more cross platform friendly... I could do it across all the vue-templates if required.

Cheers
Rowan

**Comment by yyx990803** [comment]
@rowanwins yes please! I think this is only needed for browserify-based templates.
