### ISSUE TITLE
Issue globbing `./static/*` to dist

### ISSUE THREAD

**Issue by ChickenNuggers** [vuejs-templates/browserify#28]
```
⠋ building for production...cp: no such file or directory: static/*
```

I'm pretty sure you can use the `node-glob` package to "properly" implement this, or use an automated shell system that allows actually running as a shell rather than just the commands themselves.

**Comment by zigomir** [comment]
@ChickenNuggers not sure what do you mean by that. I can't find any `static` reference in this repo.

**Comment by ChickenNuggers** [comment]
Sorry. Wrong repo. I can't actually find the right one. >_>
