### ISSUE TITLE
How to use sass

### ISSUE THREAD

**Issue by voquanghoa** [vuejs-templates/browserify#31]
Hello, 

I want to use sass instead of scss/css. So when I write
```lang=css
<style lang="sass?indentedSyntax">
#TopHeader
    width: 100%
    background: #5699D0
    color: #fff
</style>
```
it does not work.

Please help me how to config the project to use sass

Thank you

**Comment by tohjustin** [comment]
I had the same problem as you too but [Vueify](https://github.com/vuejs/vueify) seems only supports **stylus, less & scss** out of the box, so `<style lang="sass>` is implied as using **scss**. If you really want to use sass, you should try out the [webpack](https://github.com/vuejs-templates/webpack) template instead

**Comment by voquanghoa** [comment]
Ok. Thank you. So I will close this issue
