### ISSUE TITLE
Project and installed plugin getting different build of Vue

### ISSUE THREAD

**Issue by wxsms** [vuejs-templates/browserify#52]
I have a lib that exports via webpack with Vue specify as external:

```
// webpack config
{
  ...
  externals: {
    vue: {
      root: 'Vue',
      commonjs: 'vue',
      commonjs2: 'vue',
      amd: 'vue'
    }
  },
  output: {
    ...
    libraryTarget: 'umd'
  },
  ...
}
```

(actually it is a project based on official webpack template)

And I tried to use this lib in a simple project created by official browserify template:

```javascript
// main.js
import Vue from 'vue'
import * as mylib from 'mylib'

Vue.use(mylib)
```

There, strange thing happens. **The project itself is using `vue.common.js` build, but the lib is getting `vue.runtime.common.js`** (I swear that nothing else has changed beside `main.js` in the template project).

If I call `console.log(Vue.version, typeof Vue.compile)` in both `main.js` inside project and the lib, here's what I get:

![image](https://user-images.githubusercontent.com/5960988/33514371-a6cff450-d78d-11e7-94ee-3040e01713b3.png)

Is this a bug? how can I get the same build as the project in my lib? (different build causes strange warnings)

--------

update: 

* no matter how I change the build in browserify project, the plugin lib is always getting `vue.runtime.common.js`
* the lib works perfect with webpack projects or use directly in browser. it just happens in browserify projects.

**Comment by ahc-andrew** [comment]
@wxsms did you solve this?

**Comment by wxsms** [comment]
@ahc-andrew No. I close this because no responses from maintainer :cry:
