### ISSUE TITLE
JS only

### ISSUE THREAD

**Issue by thany** [vuejs-templates/browserify#9]
I did exactly this:

```
npm install -g vue-cli
vue init browserify my-project
cd my-project
npm install
npm run dev
```

And then opened http://localhost:8080.
Empty page (well, only a heading, that is), which seems fine, since it's supposed to be an empty project. But here the thing: it doesn't output any css. It manages to inject css inline in the DOM, but it doesn't create a proper css file and reference to that in the html. What it should do: output a html file with a new `<link>` tag in it, and output a css file as well with all compiled css.

Injecting css like this is absolutely horrible for performance.

**Comment by yyx990803** [comment]
Use Webpack + vue-loader if you want CSS extraction.

**Comment by thany** [comment]
Not just vue-loader, you need a whole lot more than that. But still what did you mean by "if you want"? I mean, who seriously wants to bloat their DOM with CSS, and injected by javascript to make it worse?

**Comment by yyx990803** [comment]
@thany it works pretty well in practice for small and medium sized projects. It only becomes problematic when you have hundreds of different components, in which case you should be using Webpack + vue-loader instead, which offers CSS extraction, dedupe, minification etc. If you are too lazy to research and set it up, just use vue-cli. Or, you can contribute to add CSS extraction support to vueify.
